# Install necessary libraries
```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(caret)
library(knitr) 
library(pscl)
library(plotROC)
library(pROC)
library(scales)
options(scipen = 999)
root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

# Main Property Dataset
```{r}
properties <- read.csv("opa_properties_public.csv")
colnames(properties)
table(properties$homestead_exemption)
length(which(properties$homestead_exemption==0))
length(which(properties$homestead_exemption==100000))
sum(is.na(properties$homestead_exemption))

max(properties$homestead_exemption)
which(properties$homestead_exemption == max(properties$homestead_exemption))
properties[566284, ]

# to send to Maggy White
length(which(properties$homestead_exemption>100000))
propertiesfiltered <- properties %>% filter(homestead_exemption >100000)
write.csv(propertiesfiltered, file = "properties_exceeding_exemption.csv")

ggplot(properties, aes(y = homestead_exemption)) + 
  geom_boxplot()

propertieshomestead <- properties %>% filter(homestead_exemption != 0)
propertieshomestead$exceed <- ifelse(propertieshomestead$homestead_exemption > 100000, "exceed", "within")
table(propertieshomestead$exceed)
mean(propertieshomestead$market_value, na.rm = TRUE)
median(propertieshomestead$market_value, na.rm = TRUE)
mean(propertieshomestead$sale_price, na.rm = TRUE)
median(propertieshomestead$sale_price, na.rm = TRUE)

propertiesNOThomestead <- properties %>% filter(homestead_exemption == 0)
mean(propertiesNOThomestead$market_value, na.rm = TRUE)
median(propertiesNOThomestead$market_value, na.rm = TRUE)
mean(propertiesNOThomestead$sale_price, na.rm = TRUE)
median(propertiesNOThomestead$sale_price, na.rm = TRUE)

mean(propertieshomestead$total_livable_area, na.rm = TRUE)
median(propertieshomestead$total_livable_area, na.rm = TRUE)
mean(propertiesNOThomestead$total_livable_area, na.rm = TRUE)
median(propertiesNOThomestead$total_livable_area, na.rm = TRUE)


ggplot(propertieshomestead, aes(x=market_value)) + 
  geom_histogram(color="black", fill="white", bins = 100)

ggplot(propertiesNOThomestead, aes(x=market_value)) + 
  geom_histogram(color="black", fill="white", bins = 100)

table(propertiesNOThomestead$zoning)

filtered_properties <- properties %>%
  mutate(homestead_group = ifelse(homestead_exemption == 0, "No Exemption", "With Exemption"))

# Create the bar chart
ggplot(filtered_properties, aes(x = zoning, fill = homestead_group)) +
  geom_bar(position = "dodge") +
  scale_fill_manual(values = c("No Exemption" = "red", "With Exemption" = "blue")) +
  labs(
    title = "Comparison of Zoning Categories by Homestead Exemption Status",
    x = "Zoning",
    y = "Count",
    fill = "Homestead Exemption"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

# Preliminary Logit Regression Model
```{r}
properties_model <- properties %>%
  mutate(exemption = ifelse(homestead_exemption == 0, 0, 1))
table(properties_model$exemption)
set.seed(3456)
colSums(is.na(churnTest))
trainIndex <- createDataPartition(properties_model$exemption, p = .50,
                                  list = FALSE,
                                  times = 1)
churnTrain <- properties_model[ trainIndex,]
churnTest  <- properties_model[-trainIndex,]

churnreg1 <- glm(exemption ~ .,
                 data=churnTrain %>% 
                   dplyr::select(sale_price, market_value, total_area, zip_code, geographic_ward, exemption),
                 family="binomial" (link="logit"))
testProbs <- data.frame(Outcome = as.factor(churnTest$exemption),
                        Probs = predict(churnreg1, churnTest, type= "response"))


summary(churnreg1)
pR2(churnreg1)[4]

ggplot(testProbs, aes(x = Probs, fill = as.factor(Outcome))) + 
  geom_density() +
  facet_grid(Outcome ~ .) +
  scale_fill_discrete() + xlim(0, 1) +
  labs(x = "Homestead Exemption", y = "Density of probabilities",
       title = "Distribution of predicted probabilities by observed outcome") +
  plotTheme() + theme(strip.text.x = element_text(size = 18),
                      legend.position = "none")

testProbs <- 
  testProbs %>%
  mutate(predOutcome  = as.factor(ifelse(testProbs$Probs > 0.5 , 1, 0)))

head(testProbs)

caret::confusionMatrix(testProbs$predOutcome, testProbs$Outcome, 
                       positive = "1")

#looking at predicted to have exemption but did not have exemption, which is false negative
ggplot(testProbs, aes(d = as.numeric(testProbs$Outcome), m = Probs)) +
  geom_roc(n.cuts = 50, labels = FALSE, colour = "#FE9900") +
  style_roc(theme = theme_grey) +
  geom_abline(slope = 1, intercept = 0, size = 1.5, color = 'grey') +
  labs(title = "ROC Curve - churnModel")

```


# Commercial Activity Licenses Dataset

```{r}
comlicenses <- read.csv("com_act_licenses.csv")
head(comlicenses, 10)
colnames(comlicenses)
check <- as.data.frame(table(comlicenses$ownercontact1mailingaddress))
comlicensesaddress <- comlicenses %>% mutate_all(na_if,"")
comlicensesaddress <- comlicenses
comlicensesaddress[comlicensesaddress == ""] <- NA
sum(is.na(comlicensesaddress$ownercontact1mailingaddress))
checkah <- as.data.frame(table(comlicensesaddress$ownercontact1mailingaddress))

```

# Assessment History
```{r}
assessments <- read.csv("assessments.csv")
colnames(assessments)
head(assessments, 10)

```




# Property Transfers
```{r}
transfers <- read.csv("RTT_SUMMARY.csv")
colnames(transfers)
table(transfers$document_type)

```



# Tax balances
```{r}
balances <- read.csv("real_estate_tax_balances_zip_code.csv")

```

